<?php
    $query = $db->prepare('SELECT * FROM categories');
    $query->execute();
    $categories = $query->fetchAll(PDO::FETCH_ASSOC);
?>

<header class="navbar bg-dark navbar-expand-lg bg-body-tertiary px-3" data-bs-theme="dark">
    <nav class="collapse navbar-collapse" id="navbarSupportedContent">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="index.php?route=home">Home</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Categories
                </a>
                <ul class="dropdown-menu">
                    <?php foreach($categories as $category) { ?>
                        <li><a class="dropdown-item" href="index.php?route=categories&category=<?= $category["name"] ?>"><?= ucfirst($category["name"]) ?></a></li>
                    <?php } ?>
                </ul>
            </li>
        </ul>
    </nav>
</header>