<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8" />
		<title>Exercice Routeur MVC</title>
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
              crossorigin="anonymous">
        <link rel="stylesheet"
              href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
	</head>
	<body>
		<?php
			if(isset($_SESSION['email'])) {
			?>
			<header>
				<nav>
					<ul>
						<li>
							<a href="index.php?route=chat">chat</a>
						</li>
						<li>
							<a href="index.php?route=about">a propos</a>
						</li>
					</ul>
				</nav>
			</header>
			<?php
			}
		?>
		<?php
			require "templates/category.phtml";
			require "templates/channel.phtml";
		?>
	</body>
</html>