<main class="container py-5">
    <form>
        <fieldset class="my-1">
            <label for="username" class="form-label">
            <?= $this->translator->translate("login_choose_name_label")?>
            </label>
            <input type="text" name="username" id="username" class="form-control"/>
        </fieldset>
        <fieldset class="my-1">
            <label for="email" class="form-label">
            <?= $this->translator->translate("login_email_label")?>
            </label>
            <input type="email" name="email" id="email" class="form-control"/>
        </fieldset>
        <fieldset class="my-1">
            <label for="password" class="form-label">
            <?= $this->translator->translate("login_password_label") ?>
            </label>
            <input type="password" name="password" id="password" class="form-control"/>
        </fieldset>
        <fieldset class="my-1">
            <label for="confirm-password" class="form-label">
            <?= $this->translator->translate("login_password_label") ?>
            </label>
            <input type="password" name="confirm-password" id="confirm-password" class="form-control"/>
        </fieldset>
        <fieldset class="my-4">
            <button type="submit" class="btn btn-primary"><?= $this->translator->translate("login_link_text") ?></button>
        </fieldset>
    </form>
    <p>
    <?= $this->translator->translate("login_register_text") ?> <a href="index.php"> <?= $this->translator->translate("login_link_text") ?> </a>
    </p>
</main>