
<!-- header en local -->

 <!--<header>
    <nav>
        <ul>
            <li>
                <a href="http://localhost:3000/bre01-php-j2/exos-php-j2/require//?route=home">Accueil</a>
            </li>
            <li>
                <a href="http://localhost:3000/bre01-php-j2/exos-php-j2/require//?route=about">À propos</a>
            </li>
            <li>
                <a href="http://localhost:3000/bre01-php-j2/exos-php-j2/require//?route=contact">Contact</a>
            </li>
        </ul>
    </nav>
</header> -->


<!-- header ide -->

<header>
    <nav>
        <ul>
            <li>
                <a href="https://eddyfrair.sites.3wa.io/php/module4-php/bre01-php-j2/exos-php-j2/require//?route=home">Accueil</a>
            </li>
            <li>
                <a href="https://eddyfrair.sites.3wa.io/php/module4-php/bre01-php-j2/exos-php-j2/require//?route=about">À propos</a>
            </li>
            <li>
                <a href="https://eddyfrair.sites.3wa.io/php/module4-php/bre01-php-j2/exos-php-j2/require//?route=contact">Contact</a>
            </li>
        </ul>
    </nav>
</header>