<?php

$id = null;

if(isset($_GET["id"])) {
    $id = $_GET["id"];

    $query = $db->prepare('SELECT * FROM users WHERE id = :id');
    $parameters = [
        'id' => $id
    ];
    $query->execute($parameters);
    $user = $query->fetch(PDO::FETCH_ASSOC);
}

?>

<?php
if($id !== null)
{
 ?>
    <main class="container py-5">
        <h1>
            Modifier un utilisateur
        </h1>
        <form action="logic/edit-user.php" method="POST" class="mt-5">
            <input type="hidden" id="userId" name="userId" value="<?= $user["id"] ?>" />
            <fieldset>
                <label for="email" class="form-label">Email</label>
                <input type="email" id="email" name="email" class="form-control" value="<?= $user["email"] ?>"/>
            </fieldset>
            <fieldset>
                <label for="password" class="form-label">Mot de passe</label>
                <input type="password" id="password" name="password" class="form-control" value="<?= $user["password"] ?>"/>
            </fieldset>
            <fieldset>
                <label for="firstName" class="form-label">Prénom</label>
                <input type="text" id="firstName" name="firstName" class="form-control" value="<?= $user["first_name"] ?>"/>
            </fieldset>
            <fieldset>
                <label for="lastName" class="form-label">Nom</label>
                <input type="text" id="lastName" name="lastName" class="form-control" value="<?= $user["last_name"] ?>"/>
            </fieldset>
            <button type="submit" class="mt-3 btn btn-primary">Sauvegarder</button>
        </form>
    </main>
<?php
}
else
{
    ?>
    <main class="container py-5 text-center">
        <h1>Utilisateur inconnu</h1>
    </main>
<?php
}
?>
