<?php

if(isset($_GET["id"]))
{
    $id = $_GET["id"];

    $query = $db->prepare('SELECT * FROM users WHERE id = :id');
    $parameters = [
        'id' => $id
    ];
    $query->execute($parameters);
    $user = $query->fetch(PDO::FETCH_ASSOC);


    ?>
    <main class="container py-5 text-center">
        <h1><?= $user["first_name"] ?> <?= $user["last_name"] ?></h1>
        <h2><?= $user["email"] ?></h2>
    </main>
    <?php
}
else
{
    ?>
    <main class="container py-5 text-center">
        <h1>Utilisateur inconnu</h1>
    </main>
<?php
}
?>

