<?php 
$categories = $pageController->categoryShow(); 

 ?>
<section>
    <h1>Catégories<a href="index.php?route=create-category">+</a> </h1>
    <ul>
        <ul>
        <?php foreach ($categories as $category) 
        {
            
            $channels = $pageController->channelShow();
        ?>
                    
            <h2><?= $category->getCategoryName();?><a href="index.php?route=create-channel&id=<?php echo $category->getId(); ?>">+</a></h2> 

            <?php foreach ($channels as $channel)
            { 
                if($category->getId() === $channel->getIdCategory())   
                {
                ?>

                    <li><a href="index.php?route=channel&id=<?= $channel->getId();?>"><?= $channel->getChannelName();?></a></li>
                
                <?php
                }         
            }
            ?>
        
        <?php
        }
        ?>
                
        </ul>
    </ul>
</section>