<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8" />
		<title>Exercice Routeur MVC</title>
		<link rel="stylesheet" href="assets/styles/css/style.css" type="text/css" />
	</head>
	<body>        
		<header class="header">
			<div class="logo">
				<h1>Distorsion</h1>
				<img src="assets/img/logo.png"></img>	
			</div>
				<nav>
					<ul class="navigation">
						<li>
							<a href="index.php?route=chat">Chat</a>
						</li>
						<li>
							<a href="index.php?route=about">A propos</a>
						</li>
					</ul>
				</nav>
	    </header>
	    <main>
		<?php
			require "templates/category.phtml";
			require "templates/channel.phtml";
			require "templates/$route.phtml";
		?>
	    </main>
	    

	</body>
</html>