<?php
    if(isset($_GET["id"]))
    {
        $query = $db->prepare('SELECT * FROM users WHERE id = :id');
        $parameters = [
            'id' => $_GET['id']
            ];
            $query->execute($parameters);
            $id = $query->fetch(PDO::FETCH_ASSOC);
            var_dump($id);

    }


    
?>

<main class="container py-5">
    <h1>
        Modifier un utilisateur
    </h1>
    <form class="mt-5" action="logic/edit-user.php" method="POST">
        <input type="hidden" id="userId" name="userId" value=<?php echo $_GET["id"]; ?> />
        <fieldset>
            <label for="email" class="form-label"><?php echo $id["email"]; ?></label>
            <input type="email" id="email" name="email" class="form-control" />
        </fieldset>
        <fieldset>
            <label for="password" class="form-label"><?php echo $id["password"]; ?></label>
            <input type="password" id="password" name="password" class="form-control" />
        </fieldset>
        <fieldset>
            <label for="firstName" class="form-label"><?php echo $id["firstname"]; ?></label>
            <input type="text" id="firstName" name="firstName" class="form-control" />
        </fieldset>
        <fieldset>
            <label for="lastName" class="form-label"><?php echo $id["lastname"]; ?></label>
            <input type="text" id="lastName" name="lastName" class="form-control" />
        </fieldset>
        <button type="submit" class="mt-3 btn btn-primary">Sauvegarder</button>
    </form>
</main>