<?php

?>

<main class="container py-5">
    <h1>
        Liste des utilisateurs
    </h1>
    <a href="" class="btn btn-primary mt-3"><span class="bi-plus-circle-fill"></span> Créer un utilisateur</a>
    <table class="my-5 table table-striped">
        <thead>
            <tr>
                <th>
                    #
                </th>
                <th>
                    Email
                </th>
                <th>
                    Mot de passe
                </th>
                <th>
                    Prénom
                </th>
                <th>
                    Nom
                </th>
                <th>
                    Actions
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    #
                </td>
                <td>
                    -
                </td>
                <td>
                    -
                </td>
                <td>
                    -
                </td>
                <td>
                    -
                </td>
                <td>
                    <a href="" class="btn btn-primary"><scan class="bi-eye-fill"></scan></a>
                    <a href="" class="btn btn-success"><scan class="bi-pencil-fill"></scan></a>
                    <a href="" class="btn btn-danger"><scan class="bi-trash-fill"></scan></a>
                </td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <th>
                    #
                </th>
                <th>
                    Email
                </th>
                <th>
                    Mot de passe
                </th>
                <th>
                    Prénom
                </th>
                <th>
                    Nom
                </th>
                <th>
                    Actions
                </th>
            </tr>
        </tfoot>
    </table>
</main>