<?php
    if(isset($_GET["id"]))
    {
        $query = $db->prepare('SELECT * FROM users WHERE id = :id');
        $parameters = [
            'id' => $_GET['id']
            ];
            $query->execute($parameters);
            $id = $query->fetch(PDO::FETCH_ASSOC);

    }


    
?>

<main class="container py-5 text-center">
    <h1><?php echo $id["firstname"] . " " . $id["lastname"]; ?></h1>
    <h2><?php echo $id["email"]; ?></h2>
</main>