version: '3.9'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_test_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 0Z{qZ@eePtSiR]U
      MYSQL_DATABASE: test_db
      MYSQL_USER: test
      MYSQL_PASSWORD: udstJn?CgCDI2nS2

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - .:/var/www/html/wp-content/
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: test
      WORDPRESS_DB_PASSWORD: udstJn?CgCDI2nS2
      WORDPRESS_DB_NAME: test_db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db

volumes:
  db_test_data: {}