<?php
    $home_posts = [];

    foreach($posts as $key => $item)
    {
        $home_posts[$key] = [];

        foreach($item as $idx => $post)
        {
            if($idx < 3)
            {
                $home_posts[$key][$idx] = $post;
            }
        }
    }

    $query = $db->prepare('SELECT categories.* FROM categories ');

    $query->execute();
    $cats = $query->fetchAll(PDO::FETCH_ASSOC); 

    $query2 = $db->prepare('SELECT posts.* FROM posts JOIN categories ON posts.categories_id = categories.id ORDER BY  categories.nom LIMIT 9');

    $query2->execute();
    $posts = $query2->fetchAll(PDO::FETCH_ASSOC); 
var_dump($posts);
?>


<main id="home" class="p-3">
    <h1 class="text-center m-5">Ze blog</h1>
    <?php
        foreach($cats as $cat)
        {
            ?>
                <section class="my-5">
                    <h2><?= ucfirst($cat["nom"])?></h2>
                    <ul class="row p-0">
                        <?php
                        foreach($posts as $key => $post)
                        {
                            if($key < 3 && $post["categories.nom"] = $cat["nom"])
                            {
                            ?>
                            <li class="col m-1">
                                <article class="card">
                                    <header class="card-header p-0">
                                        <img src="https://picsum.photos/id/1/550/250" class="card-img-top" alt="man typing on a laptop" />
                                        <h3 class="card-title px-2 py-3">
                                            <?= $post["title"] ?>
                                        </h3>
                                    </header>
                                    <section class="card-body p-2">
                                        <p class="card-text">
                                            <?= $post["excerpt"] ?>
                                        </p>
                                    </section>
                                    <footer class="p-2">
                                        <a href="index.php?route=article&category=<?= $category; ?>&post=<?= $idx; ?>" class="btn btn-primary">Lire l'article</a>
                                    </footer>
                                </article>
                            </li>
                            <?php
                        }}
                        ?>
                    </ul>
                </section>
            <?php
        }
    ?>
</main>