<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">  
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>  
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="style.css">
    <title>mini-projet-cv</title>
</head>
<body>
    <header class="header">
        <h1></h1>
        <p>Intitulé du poste</p>
    </header>
    <main class="cont-cv">
        <section>
            <h2 class="">INFORMATIONS</h2>
            <article class="contact">
                <h3 >Contact</h3>
                <p class="">Email</p>
                <pre><a href ="mailto:email@example.com">   email@example.com</a></pre>
                <p class="">Téléphone</p>
                <pre><a href ="tel:01 02 03 04 05">   01 02 03 04 05</a></pre>
                <p class="">Linkedin</p>
                <pre><a href="https://linkedin.com/example">   https://linkedin.com/example</a></pre>
                <p class="">Github</p>
                <pre><a href="https://:github.com/example">   https://github.com/example</a></pre>
            </article>
            <article>
                <h3 class="">Biographie</h3>
                <p></p>
            </article>
            <article>
                <h3 class="">Loisirs</h3>
                <ul>
                    <li></li>
                </ul>
            </article>
        </section>
        <section>
            <h2 class="">COMPETENCES</h2>
            <article>
            <h3 class="">Langage de programmation</h3>
                <ul>
                    <li></li>
                </ul>
            </article>
            <article>
            <h3 class="">Framewrks & Librairies</h3>
                <ul>
                    <li></li>
                </ul>
            </article>
            <article>
            <h3 class="">Logiciels</h3>
                <ul>
                    <li></li>
                </ul>
            </article>
            <article>
            <h3 class="">Langues</h3>
                <ul>
                    <li></li>
                </ul>
            </article>
        </section>
    </main>
</body>
</html>