<main>
	<h1>Connexion</h1>
    <section>
        <h3>Connexion</h3>
        <form id="loginForm" action="index.php?route=check-connexion" method="POST">
            <fieldset>
                <label for="loginEmail">
                    Email
                </label>
                <input type="email" name="loginEmail" id="loginEmail" />
            </fieldset>
            <fieldset>
                <label for="loginPassword">
                    Mot de passe
                </label>
                <input type="password " name="loginPassword" id="loginPassword" />
            </fieldset>
            <button type="submit">Se connecter</button>
        </form>
    </section>
</main>