<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8" />
		<title>Exercice Routeur MVC</title>
	</head>
	<body>
		<header>
			<nav>
				<ul>
					<li>
						<a href="index.php">Accueil</a>
					</li>
					<li>
						<a href="index.php?route=connexion">Connexion</a>
					</li>
					<li>
						<a href="index.php?route=inscription">Inscription</a>
					</li>
				</ul>
			</nav>
		</header>
		<?php
			if($route === "connexion")
            {
                require "templates/connexion.phtml";
            }
            else if($route === "inscription")
            {
                require "templates/inscription.phtml";
            }
            else if($route === "espace-perso")
            {
                require "templates/espace-perso.phtml";
            }
            else
            {
                require "templates/404.phtml";
            }
		?>
	</body>
</html>